### ISSUE TITLE
[BUG] TypeError: THREE.BufferAttribute: array should be a Typed Array

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#46]
**Scope**
- [ x] core
- [ ] cannon
- [ ] postprocessing
- [ ] soba

**Describe the bug**
ERROR TypeError: THREE.BufferAttribute: array should be a Typed Array.
    at new BufferAttribute (three.module.js:8981:10)
    at NgtBufferAttribute.init (angular-three-core.mjs:3230:67)
    at angular-three-core.mjs:3211:18
    at ZoneDelegate.invoke (zone.js:372:1)
    at Zone.run (zone.js:134:1)
    at NgZone.runOutsideAngular (core.mjs:25371:1)
    at NgtBufferAttribute.set attributeArgs [as attributeArgs] (angular-three-core.mjs:3210:21)
    at NgtBufferAttribute.set args [as args] (angular-three-core-attributes.mjs:13:9)
    at Object.ngOnChangesSetInput [as setInput] (core.mjs:1502:1)
    at setInputsForProperty (core.mjs:10959:1)
**To Reproduce**
Template contains the following
    &lt;ngt-line #line="ngtLine" &gt;
          &lt;ngt-buffer-geometry&gt;
            &lt;ngt-buffer-attribute attach="position" [args]="[[0, 0, 0, 0, 0, - 1], 3]"&gt;&lt;/ngt-buffer-attribute&gt;
          &lt;/ngt-buffer-geometry&gt;
          &lt;ngt-line-basic-material [parameters]="{ vertexColors: true, blending: blending }"></ngt-line-basic-material&gt;
        &lt;/ngt-line&gt;
Get above in browser console for ngt-buffer-attribute attach="position"

**Expected behavior**
Should work without error.  Replacing with a variable doesn't work either.

**Additional context**
Converting https://github.com/mrdoob/three.js/blob/master/examples/webxr_vr_cubes.html to @angular/three.  
I have the whole example converted to @angular/three, but trying to replace

    const geometry = new BufferGeometry();
    geometry.setAttribute('position', new Float32BufferAttribute([0, 0, 0, 0, 0, - 1], 3));
    geometry.setAttribute('color', new Float32BufferAttribute([0.5, 0.5, 0.5, 0, 0, 0], 3));
    const material = new LineBasicMaterial({ vertexColors: true, blending: AdditiveBlending });
    return new Line(geometry, material);

Want to make the track-pointer line attached to XR controller be something that can be declared, instead of hard-coded.

**Comment by IRobot1** [comment]
After a few more tries, I figured it out.  Declare a variable
  position = new Float32Array([0, 0, 0, 0, 0, - 1]);
then use the following in the template
 <ngt-buffer-attribute attach="position" [args]="[position, 3]"></ngt-buffer-attribute>
