### ISSUE TITLE
Error after adding ngt-physics

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#49]
Using latest 4.0.2 version of @angular/three. 
Added cannon as follows
npm i @angular-three/cannon cannon-es
ng serve working fine.

Wrapped ngt-group with ngt-physics as follows
<ngt-physics>
  <ngt-group #group="ngtGroup" [name]="'room'">
    <ngt-mesh *ngFor="let item of shapes" 
              [position]="item.position" [rotation]="item.rotation" [scale]="item.scale" [castShadow]="true" [receiveShadow]="true"
              #mesh="ngtMesh">
      <ngt-mesh-standard-material [parameters]="{ color: item.color, roughness: 0.7, metalness:0.0 }"></ngt-mesh-standard-material>
      <ngt-box-geometry *ngIf="item.shapename=='box'" [args]="[0.2, 0.2, 0.2]"></ngt-box-geometry>
      <ngt-cone-geometry *ngIf="item.shapename=='cone'" [args]="[0.2, 0.2, 64]"></ngt-cone-geometry>
      <ngt-cylinder-geometry *ngIf="item.shapename=='cylinder'" [args]="[ 0.2, 0.2, 0.2, 64]"></ngt-cylinder-geometry>
      <ngt-icosahedron-geometry *ngIf="item.shapename=='icosahedron'" [args]="[ 0.2, 8]"></ngt-icosahedron-geometry>
      <ngt-torus-geometry *ngIf="item.shapename=='torus'" [args]="[ 0.2, 0.04, 64, 32]"></ngt-torus-geometry>
    </ngt-mesh>
  </ngt-group>
</ngt-physics>

Browser console shows this error.

ERROR DOMException: Failed to construct 'Worker': Script at 'file:///C:/Users/adria/source/repos/angular-vr/node_modules/@angular-three/cannon/fesm2015/utils/worker.js' cannot be accessed from origin 'http://localhost:4200'.
    at new NgtPhysicsStore (http://localhost:4200/vendor.js:20051:15)
    at NodeInjectorFactory.NgtPhysicsStore_Factory [as factory] (http://localhost:4200/vendor.js:20280:10)
    at getNodeInjectable (http://localhost:4200/vendor.js:42415:44)
    at searchTokensOnInjector (http://localhost:4200/vendor.js:42352:16)
    at getOrCreateInjectable (http://localhost:4200/vendor.js:42296:38)
    at Module.ɵɵdirectiveInject (http://localhost:4200/vendor.js:53256:12)
    at NodeInjectorFactory.NgtPhysics_Factory [as factory] (http://localhost:4200/vendor.js:20409:95)
    at getNodeInjectable (http://localhost:4200/vendor.js:42415:44)
    at instantiateAllDirectives (http://localhost:4200/vendor.js:49148:27)
    at createDirectivesInstances (http://localhost:4200/vendor.js:48497:5)

Is there something I should be adding to angular.json or tsconfig.json?

**Comment by nartc** [comment]
@IRobot1 Do not try 4.1.0. I tried fixing the error but it didn't work 😅. Apparently, I'd need to bundle the Worker somehow :)
