### ISSUE TITLE
ERROR Error: NGT_CANNON_BODY_TYPE is required

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#54]
After adding cannon physics around an object, the following appears in the browser console.

ERROR Error: NGT_CANNON_BODY_TYPE is required
    at new NgtCannonBodyController (angular-three-cannon-bodies.mjs:136:19)
    at NodeInjectorFactory.NgtCannonBodyController_Factory [as factory] (angular-three-cannon-bodies.mjs:342:1)
    at getNodeInjectable (core.mjs:3565:1)
    at instantiateAllDirectives (core.mjs:10298:1)
    at createDirectivesInstances (core.mjs:9647:1)
    at Module.ɵɵelementStart (core.mjs:14541:1)
    at PlaneComponent_Template (storybook-plane.component.ts:7:9)
    at executeTemplate (core.mjs:9618:1)
    at renderView (core.mjs:9421:1)
    at renderComponent$1 (core.mjs:10702:1)

**Comment by IRobot1** [comment]
To fix, import NgtPhysicPlaneModule
