### ISSUE TITLE
see - issue 49

### ISSUE THREAD

**Issue by Anna-McCartain** [nartc/angular-three#77]
I am having same issue as 49 although have completed all steps in the issue 

https://github.com/nartc/angular-three/issues/49 

vendor.js:60782 ERROR Error: Uncaught (in promise): SecurityError: Failed to construct 'Worker': Script at 'file:///Users/annamccartain/Desktop/project-repo/angular/the-city/node_modules/@angular-three/cannon/fesm2015/utils/worker' cannot be accessed from origin 'http://localhost:4200'.
Error: Failed to construct 'Worker': Script at 'file:///Users/annamccartain/Desktop/project-repo/angular/the-city/node_modules/@angular-three/cannon/fesm2015/utils/worker' cannot be accessed from origin 'http://localhost:4200'.
    at new NgtPhysicsStore (vendor.js:27039:15)
    at NodeInjectorFactory.NgtPhysicsStore_Factory [as factory] (vendor.js:27268:10)
    at getNodeInjectable (vendor.js:57862:44)
    at searchTokensOnInjector (vendor.js:57799:16)
    at getOrCreateInjectable (vendor.js:57743:38)
    at Module.ɵɵdirectiveInject (vendor.js:68693:12)
    at NodeInjectorFactory.NgtPhysics_Factory [as factory] (vendor.js:27397:95)
    at getNodeInjectable (vendor.js:57862:44)
    at instantiateAllDirectives (vendor.js:64595:27)
    at createDirectivesInstances (vendor.js:63944:5)
    at resolvePromise (polyfills.js:4328:31)
    at resolvePromise (polyfills.js:4282:17)
    at polyfills.js:4394:17
    at ZoneDelegate.invokeTask (polyfills.js:3521:31)
    at Object.onInvokeTask (vendor.js:79772:33)
    at ZoneDelegate.invokeTask (polyfills.js:3520:60)
    at Zone.runTask (polyfills.js:3293:47)
    at drainMicroTaskQueue (polyfills.js:3697:35)
    at ZoneTask.invokeTask [as invoke] (polyfills.js:3606:21)
    at invokeTask (polyfills.js:4715:14)
defaultErrorLogger @ vendor.js:60782
handleError @ vendor.js:60829
next @ vendor.js:80324
next @ vendor.js:14864
_next @ vendor.js:14833
next @ vendor.js:14804
(anonymous) @ vendor.js:14655
errorContext @ vendor.js:17941
next @ vendor.js:14650
emit @ vendor.js:76720
(anonymous) @ vendor.js:79811
invoke @ polyfills.js:3487
run @ polyfills.js:3249
runOutsideAngular @ vendor.js:79684
onHandleError @ vendor.js:79811
handleError @ polyfills.js:3491
runGuarded @ polyfills.js:3262
api.microtaskDrainDone @ polyfills.js:4189
drainMicroTaskQueue @ polyfills.js:3704
invokeTask @ polyfills.js:3606
invokeTask @ polyfills.js:4715
globalZoneAwareCallback @ polyfills.js:4741

**Comment by Anna-McCartain** [comment]
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/68697352/160865817-a3235e86-e595-44ca-a90e-12aad36d65dd.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/68697352/160865905-9a79cc9f-91c7-45da-9295-cc18b87d1277.png">

warnings on worker load and plane is coming out blank
